---
title: 'Trichogramma range expansions (genetics and dynamics): 4- experimental data (supplementary)'
author: "Maxime Dahirel"
date: "31/03/2020"
output: 
  html_document:
    theme: yeti
    toc: TRUE
    toc_float: TRUE
    code_download: TRUE
editor_options: 
  chunk_output_type: console
---


```{r}
data_genetics %>% 
  filter(Generation==0) %>% 
  ggplot+
  geom_boxplot(aes(x=factor(Mix),y=Hexp),alpha=0.2)+
  geom_jitter(aes(x=Mix,y=Hexp),pch=20,size=4)+
  scale_y_continuous(name = "Genetic diversity at the start of the experiment (Hexp)",limits=c(0.1,0.45)) + 
  scale_x_discrete("Genetic Mix")+
  theme_bw()
```


```{r}
data_popsize <- data_popsize_temp %>% 
  group_by(Generation,landscapeID) %>% 
  filter(Patch<= 0.25*max(Patch)) ## we only keep "core" pops
  


mod_popsize <- brm(bf(Peggs_est~0+Treatment+(1|Macro)+(1|landscapeID/spacetimeID), 
        nlf(phi~1/invphi),
        invphi~1),
        data=data_popsize,family=Beta(link_phi="identity"),
        iter=2000,chains=4,
        prior=c(
          set_prior("normal(0,1.5)",class="b"),
          set_prior("normal(0,1)",class="sd"),
          set_prior("normal(0,1)",nlpar="invphi",lb=0)
        ),
        control=list(adapt_delta=0.99),seed=42)




newdata <- data_popsize %>% ungroup() %>% 
  mutate(Macro=Macro[1],landscapeID=landscapeID[1],spacetimeID=spacetimeID[1]) %>%  #it's just a placeholder, we plot the posterior for the "true" (grand) mean distance, without random effects
  select(Macro, Treatment) %>% 
  distinct()

### these averages are just indicative and for plotting purposes
#data_popsize_avg <- data_G0 %>% 
#  group_by(landscapeID,Treatment)%>%  
#  summarise(distmean=mean(distmean),
#            jitteredTRT=mean(jitteredTRT)) %>% ungroup()
#
## the main plot                                                           
p1 <-newdata %>% 
  add_fitted_draws(mod_popsize,re_formula=NA) %>% 
  ggplot()+
  stat_eye(aes(x=Treatment,y=.value,fill=Treatment),.width=c(0.66,0.95),slab_alpha=0.8,point_interval = mean_hdi) +
  ## we put both observed points (by macros) and the indicative averages for each each landscape
  #geom_point(data=data_G0,aes(x=jitteredTRT,y=distmean,col=Treatment),fill="white",pch=21,alpha=0.8)+
  #geom_point(data=data_G0_avg, aes(x=jitteredTRT,y=distmean,fill=Treatment),pch=21,size=2)+
  scale_fill_manual(values=TRTpalette[c(1,4)])+
  scale_colour_manual(values=TRTpalette[c(1,4)])+
  scale_x_discrete("")+
  scale_y_continuous("Mean parasitism rate in core patches",limits=c(0,1))+
  theme_bw()

## a subplot showing the difference between treatments. Keep it or put this info in text?
p2<- newdata %>% 
  add_fitted_draws(mod_popsize,re_formula=NA) %>% 
  ungroup() %>% 
  compare_levels(variable=.value,by=Treatment) %>% 
  ggplot()+
  stat_eye(aes(x=Treatment,y=.value),.width=c(0.66,0.95),fill="grey",point_interval = mean_hdi)+
  scale_x_discrete("",labels="")+
  scale_y_continuous("Difference between treatments",
                     limits=c(0,1)-invlogit(fixef(mod_popsize)["Treatmentcontrol","Estimate"])) + ##so the "difference" subplot is aligned with the main
  geom_hline(yintercept=0, lty=2) +
  theme_bw()

p1 + p2 + plot_layout(guides="collect",widths=c(4,1)) & theme_bw() &
  theme(legend.position="none")



diffs<- newdata %>% 
    add_fitted_draws(mod_popsize,re_formula=NA) %>% 
    ungroup() %>% 
    compare_levels(variable=.value,by=Treatment) %>% mutate(.diff=.value) %>% ungroup() %>% select(-c(.value,Treatment))

newdata %>% 
    add_fitted_draws(mod_popsize,re_formula=NA) %>% 
    ungroup() %>% filter(Treatment=="control") %>% left_join(diffs) %>% mean_hdi(.diff/.value)

```

