---
title: 'Trichogramma range expansions (genetics and dynamics): 5- individual-based model, analysis (supplementary)'
author: "Maxime Dahirel"
date: "31/03/2020"
output: 
  html_document:
    theme: yeti
    toc: TRUE
    toc_float: TRUE
    code_download: TRUE
editor_options: 
  chunk_output_type: console
---

```{r}
library(arm)
library(tidyverse)
library(here)

library(modelr)
library(RColorBrewer)

###inference
library(coda)
library(rstan)
library(bayesplot)
library(brms)
rstan_options(auto_write = TRUE)
options(mc.cores = 2)
library(tidybayes)
library(cowplot)
library(patchwork)
```


```{r importing-data}
data <- read_csv(file=here("NetLogo_output/model-output_supplementary.csv"))
```


```{r}


#### for analysing size of new propagules:
#### works only if all ticks are recorded

tab_propa <- data %>% 
  filter(treatment == "control" | treatment =="reduced connectedness") %>% 
  mutate(replicateID=paste(treatment,K,seedID)) %>% 
  select(treatment,K,seedID,replicateID,ticks,N_postdispersal,N_predispersal,is.front) %>% 
  #group_by(treatment,replicateID,K,ticks) %>% 
  #pivot_wider(values_from=c(N_predispersal,N_postdispersal),names_from=is.front) %>% 
  filter(N_predispersal==0  & is.front==TRUE & ticks >1) %>%  ##we only keep case where the front advanced (new pops) 
  ###remove G1 because dispersal goes in only one direction so messier for comparison to deterministic
  ungroup() %>% 
  mutate(K=factor(K)) %>% 
  select(replicateID,treatment,K,seedID,N_postdispersal,ticks)#,N_source=N_predispersal_FALSE,N_postdispersal=N_postdispersal_TRUE)

mod_propa1=brm(bf(N_postdispersal|trunc(lb=1)~0+treatment:K+(1|replicateID), ##careful, very slow
                  nlf(shape~1/invshape),
                  invshape~1),
               family=negbinomial(link_shape = "identity"),data=tab_propa,
               prior=c(set_prior("normal(0,1)",class="b"),
                       set_prior("normal(0,1)",class="sd"),
                       set_prior("normal(0,1)",nlpar="invshape")),chains=2,iter=200,seed=1989)

tab_propa %>% 
  mutate(replicateID=replicateID[1]) %>% 
  select(treatment,K,replicateID) %>% distinct() %>% add_fitted_draws(mod_propa1,re_formula=NA,scale="linear") %>% 
  ggplot()+
  #geom_boxplot(data=tab_propa,aes(x=treatment,y=ratio),alpha=0.1)+
  geom_eye(aes(x=treatment,y=exp(.value)))+ 
  scale_y_continuous("front population size at establishment (posterior mean)")+
  scale_x_discrete("landscape type")+
  facet_wrap(~paste ("K = ",K))+theme_bw()

```

